[phases.setup]
nixPkgs = ["php81", "php81Extensions.mysqli", "php81Extensions.mbstring", "php81Extensions.gd", "php81Extensions.curl", "php81Extensions.openssl", "php81Extensions.zip", "composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT router.php"
